export const arenaSummaryFixture = [
  {
    variant: "S02",
    ironEv: 5.1,
    proEv: 3.9,
    standardEv: 6.4,
    ironProGap: 1.2,
    standardAdvantage: 1.3,
    datasetHitRate: 0.004,
    proFallbackRate: 0.996,
    coveredBuckets: ["strongSDA5 top-end pressure"],
  },
  {
    variant: "D02",
    ironEv: 5.0,
    proEv: 3.6,
    standardEv: 4.2,
    ironProGap: 1.4,
    standardAdvantage: -0.8,
    datasetHitRate: 0.003,
    proFallbackRate: 0.997,
    coveredBuckets: ["strongA5 second-pressure"],
  },
];

export const divergenceRowsFixture = [
  {
    variantId: "S02",
    bucketFamily: "lowerMediumSDA5 bet-pressure",
    bucket: "lowerMediumSDA5 bet-pressure",
    handClass: "lowerMediumSDA5",
    playerCountClass: "3way",
    position: "blind",
    drawRound: 2,
    bettingRound: 1,
    pressureFamily: "bet-pressure",
    callBand: "big",
    standardAction: "CALL",
    proAction: "FOLD",
    standardEvDelta: 22,
    evGap: -32,
    standardAdvantage: 32,
    frequency: 90,
    sourceType: "test",
  },
  {
    variantId: "S02",
    bucketFamily: "strongSDA5 top-end pressure",
    bucket: "strongSDA5 top-end pressure",
    handClass: "strongSDA5",
    playerCountClass: "heads-up",
    position: "button",
    drawRound: 1,
    bettingRound: 1,
    pressureFamily: "bet-pressure",
    callBand: "small",
    standardAction: "BET",
    proAction: "CHECK",
    standardEvDelta: 0,
    evGap: 0,
    standardAdvantage: 0,
    frequency: 25,
    sourceType: "test",
  },
  {
    variantId: "D02",
    bucketFamily: "trashA5 FOLD/CALL verify",
    bucket: "trashA5 FOLD/CALL verify",
    handClass: "trashA5",
    playerCountClass: "4way+",
    position: "blind",
    drawRound: 2,
    bettingRound: 1,
    pressureFamily: "bet-pressure",
    callBand: "big",
    standardAction: "CALL",
    proAction: "FOLD",
    standardEvDelta: 8,
    evGap: -8,
    standardAdvantage: 8,
    frequency: 200,
    sourceType: "test",
  },
];
