export function s02Sample({
  playerCount = 4,
  position = "button",
  drawRound = 0,
  bettingRound = 0,
  standardAction = "CALL",
  proAction = "FOLD",
} = {}) {
  return {
    variantId: "S02",
    seed: 1,
    handId: 1,
    step: 1,
    actorSeat: 2,
    playerCount,
    position,
    drawRound,
    bettingRound,
    facingAction: "bet",
    handClass: "lowerMediumSDA5",
    legalActions: ["FOLD", "CALL", "RAISE"],
    standardAction: { type: standardAction },
    proAction: { type: proAction },
    snapshot: {
      currentBet: drawRound >= 1 ? 40 : 20,
      pot: 80,
      players: [{}, {}, { stack: 480, betThisRound: 0 }],
      metadata: {
        currentBet: drawRound >= 1 ? 40 : 20,
        potAmount: 80,
        raiseCountThisRound: 0,
        lastBettingAction: { type: "BET" },
      },
    },
  };
}

export const step28Rows = [
  ...Array.from({ length: 36 }, (_value, index) => ({
    sample: s02Sample({ position: index % 2 ? "button" : "cutoff", drawRound: 0 }),
    seed: index,
    handId: index,
    step: 1,
    standardAction: "CALL",
    proAction: "FOLD",
    delta: 24,
    ok: true,
    legality: { invalidReplay: false, legalActionMismatch: false, repairRequired: false },
  })),
  ...Array.from({ length: 4 }, (_value, index) => ({
    sample: s02Sample({ position: "small-blind", drawRound: 1 }),
    seed: 100 + index,
    handId: 100 + index,
    step: 2,
    standardAction: "CALL",
    proAction: "FOLD",
    delta: -12,
    ok: true,
    legality: { invalidReplay: false, legalActionMismatch: false, repairRequired: false },
  })),
];

export const focusedReportFixture = {
  bucket: "S02 lowerMediumSDA5 bet-pressure",
  sampleCount: 40,
  meanDelta: 20.4,
  confidence: 0.86,
  signFlipRate: 0.1,
  entropyScore: 0.28,
  repairRate: 0,
  invalidReplayCount: 0,
  deterministicReplay: true,
  observations: step28Rows.map((row) => ({
    seed: row.seed,
    handId: row.handId,
    step: row.step,
    playerCount: row.sample.playerCount,
    position: row.sample.position,
    drawRound: row.sample.drawRound,
    bettingRound: row.sample.bettingRound,
    callBand: row.sample.drawRound >= 1 ? "big" : "small",
    pressureFamily: "bet-pressure",
    pressureChain: "bet|raises=0",
    stackDepth: "deep",
    handClassStrength: "lowerMediumSDA5",
    toCallRatio: "<=0.25",
    potOddsBand: "cheap",
    standardAction: row.standardAction,
    proAction: row.proAction,
    standardEv: row.delta,
    proEv: 0,
    delta: row.delta,
    ok: row.ok,
    repairRequired: false,
    repairType: null,
  })),
};
