export const TOURNAMENT_OPPONENTS = [
  // 店舗ステージ
  {
    id: "store-satoru",
    stageId: "store",
    tier: "店舗",
    name: "サトル",
    nickname: "慎重派の学生",
    style: "Balanced",
    strength: 1,
    aggression: 0.45,
    tightness: 0.55,
    drawRate: 0.4,
    bluffFreq: 0.1,
    notes: "序盤はほぼリンプ。堅実にショーダウンまで粘るタイプ。",
  },
  {
    id: "store-miyu",
    stageId: "store",
    tier: "店舗",
    name: "ミユ",
    nickname: "自由奔放",
    style: "Loose",
    strength: 1,
    aggression: 0.38,
    tightness: 0.35,
    drawRate: 0.52,
    bluffFreq: 0.14,
    notes: "ドロー枚数を恐れず、ヒットすれば一気に押し切る。",
  },
  {
    id: "store-goro",
    stageId: "store",
    tier: "店舗",
    name: "ゴロー",
    nickname: "アナリティクス厨",
    style: "Tight",
    strength: 1,
    aggression: 0.25,
    tightness: 0.78,
    drawRate: 0.3,
    bluffFreq: 0.05,
    notes: "3カード以下で固める守備型。BTN以外ではほぼフォールド。",
  },
  {
    id: "store-naoto",
    stageId: "store",
    tier: "店舗",
    name: "ナオト",
    nickname: "先制のSB",
    style: "Aggro",
    strength: 2,
    aggression: 0.62,
    tightness: 0.42,
    drawRate: 0.36,
    bluffFreq: 0.18,
    notes: "SB/BBでのスチール率が高い。3ベット頻度も高め。",
  },
  {
    id: "store-karin",
    stageId: "store",
    tier: "店舗",
    name: "カリン",
    nickname: "読み鋭い店員",
    style: "TAG",
    strength: 2,
    aggression: 0.5,
    tightness: 0.62,
    drawRate: 0.38,
    bluffFreq: 0.12,
    notes: "BTNでのトリプルバレルが得意。終盤のショーダウン率が低い。",
  },

  // 地方ステージ
  {
    id: "local-haruka",
    stageId: "local",
    tier: "地方",
    name: "ハルカ",
    nickname: "地方の壁",
    style: "Balanced",
    strength: 3,
    aggression: 0.52,
    tightness: 0.58,
    drawRate: 0.38,
    bluffFreq: 0.12,
    notes: "ショーダウン勝率が高い。情報管理が丁寧。",
  },
  {
    id: "local-joe",
    stageId: "local",
    tier: "地方",
    name: "ジョウ",
    nickname: "圧力番長",
    style: "Aggro",
    strength: 3,
    aggression: 0.68,
    tightness: 0.4,
    drawRate: 0.35,
    bluffFreq: 0.2,
    notes: "BTNからの3カードブラフが多く、押し切り型。",
  },
  {
    id: "local-arisa",
    stageId: "local",
    tier: "地方",
    name: "アリサ",
    nickname: "EV厨",
    style: "Math TAG",
    strength: 3,
    aggression: 0.48,
    tightness: 0.7,
    drawRate: 0.33,
    bluffFreq: 0.11,
    notes: "ドロー枚数をシビアに調整する期待値プレイヤー。",
  },
  {
    id: "local-ken",
    stageId: "local",
    tier: "地方",
    name: "ケン",
    nickname: "ハイプレッシャー",
    style: "Aggro",
    strength: 2,
    aggression: 0.62,
    tightness: 0.42,
    drawRate: 0.42,
    bluffFreq: 0.18,
    notes: "SB/BBでの3ベット率が非常に高い。",
  },
  {
    id: "local-rui",
    stageId: "local",
    tier: "地方",
    name: "ルイ",
    nickname: "準鉄人",
    style: "Balanced",
    strength: 2,
    aggression: 0.52,
    tightness: 0.5,
    drawRate: 0.37,
    bluffFreq: 0.14,
    notes: "荒れ場でもバランスを崩さない中堅。",
  },

  // 全国ステージ
  {
    id: "national-ryo",
    stageId: "national",
    tier: "全国",
    name: "リョウ",
    nickname: "ブラファー",
    style: "LAG",
    strength: 4,
    aggression: 0.58,
    tightness: 0.32,
    drawRate: 0.46,
    bluffFreq: 0.25,
    notes: "キャッチングを嫌っても攻めを止めない。",
  },
  {
    id: "national-mei",
    stageId: "national",
    tier: "全国",
    name: "メイ",
    nickname: "緻密TAG",
    style: "TAG",
    strength: 4,
    aggression: 0.55,
    tightness: 0.66,
    drawRate: 0.36,
    bluffFreq: 0.16,
    notes: "UTGレンジが最も強い。終盤の押し引きが的確。",
  },
  {
    id: "national-yui",
    stageId: "national",
    tier: "全国",
    name: "ユイ",
    nickname: "高速決断",
    style: "Aggro",
    strength: 3,
    aggression: 0.6,
    tightness: 0.48,
    drawRate: 0.4,
    bluffFreq: 0.15,
    notes: "タイムバンクをほぼ使わない瞬発派。",
  },
  {
    id: "national-takuma",
    stageId: "national",
    tier: "全国",
    name: "タクマ",
    nickname: "鉄壁",
    style: "Rock",
    strength: 3,
    aggression: 0.32,
    tightness: 0.78,
    drawRate: 0.3,
    bluffFreq: 0.05,
    notes: "参加レンジが極端にタイト。ショーダウンまで粘る。",
  },
  {
    id: "national-arata",
    stageId: "national",
    tier: "全国",
    name: "アラタ",
    nickname: "速度調整役",
    style: "Balanced",
    strength: 3,
    aggression: 0.5,
    tightness: 0.52,
    drawRate: 0.37,
    bluffFreq: 0.13,
    notes: "レベル変化に合わせてペースを調整する。",
  },

  // 世界ステージ
  {
    id: "world-zen",
    stageId: "world",
    tier: "世界",
    name: "ゼン",
    nickname: "完全AI",
    style: "Solver",
    strength: 5,
    aggression: 0.7,
    tightness: 0.55,
    drawRate: 0.44,
    bluffFreq: 0.18,
    notes: "レンジミックスを徹底する最上位CPU。",
  },
  {
    id: "world-rei",
    stageId: "world",
    tier: "世界",
    name: "レイ",
    nickname: "冷徹の女王",
    style: "Tight",
    strength: 5,
    aggression: 0.5,
    tightness: 0.82,
    drawRate: 0.28,
    bluffFreq: 0.07,
    notes: "ショーダウンまで一切情報を与えない。",
  },
  {
    id: "world-akira",
    stageId: "world",
    tier: "世界",
    name: "アキラ",
    nickname: "圧殺マシン",
    style: "Hyper Aggro",
    strength: 5,
    aggression: 0.82,
    tightness: 0.35,
    drawRate: 0.5,
    bluffFreq: 0.2,
    notes: "常にレンジ上限で殴り続ける。",
  },
  {
    id: "world-hakase",
    stageId: "world",
    tier: "世界",
    name: "ハカセ",
    nickname: "理論家",
    style: "Solver",
    strength: 5,
    aggression: 0.42,
    tightness: 0.78,
    drawRate: 0.28,
    bluffFreq: 0.05,
    notes: "EVを最優先し、無駄な勝負を避ける。",
  },
  {
    id: "world-scarlet",
    stageId: "world",
    tier: "世界",
    name: "スカーレット",
    nickname: "世界の女帝",
    style: "Balanced",
    strength: 5,
    aggression: 0.66,
    tightness: 0.48,
    drawRate: 0.41,
    bluffFreq: 0.17,
    notes: "状況に応じて打ち筋を切り替える最終ボス。",
  },
];
