export const TOURNAMENT_OPPONENTS = [
  { id: 1, name: "サトル", tier: "店舗", style: "バランス", strength: 1, trait: "入門", aggr: 0.45, tight: 0.55, drawRate: 0.4, bluffFreq: 0.1, notes: "入門" },
  { id: 2, name: "ミユ", tier: "店舗", style: "ルーズ", strength: 1, trait: "初心者", aggr: 0.35, tight: 0.3, drawRate: 0.52, bluffFreq: 0.12, notes: "ルーズ" },
  { id: 3, name: "ゴロー", tier: "店舗", style: "タイト", strength: 1, trait: "守備", aggr: 0.25, tight: 0.75, drawRate: 0.35, bluffFreq: 0.05, notes: "タイト" },
  { id: 4, name: "ナオト", tier: "店舗", style: "タイヤ", strength: 2, trait: "攻め", aggr: 0.55, tight: 0.35, drawRate: 0.3, bluffFreq: 0.15, notes: "攻め" },
  { id: 5, name: "シンブ", tier: "店舗", style: "タイヤ", strength: 2, trait: "堅実", aggr: 0.4, tight: 0.6, drawRate: 0.28, bluffFreq: 0.08, notes: "堅実" },
  { id: 6, name: "カリン", tier: "地方", style: "アグレッシブ", strength: 2, trait: "攻め", aggr: 0.65, tight: 0.45, drawRate: 0.35, bluffFreq: 0.18, notes: "攻撃" },
  { id: 7, name: "ハルカ", tier: "地方", style: "バランス", strength: 3, trait: "対応", aggr: 0.5, tight: 0.6, drawRate: 0.4, bluffFreq: 0.12, notes: "対応" },
  { id: 8, name: "ジョウ", tier: "全国", style: "強気", strength: 3, trait: "圧力", aggr: 0.65, tight: 0.35, drawRate: 0.32, bluffFreq: 0.2, notes: "圧力" },
  { id: 9, name: "アリサ", tier: "全国", style: "理論派", strength: 3, trait: "EV重視", aggr: 0.45, tight: 0.7, drawRate: 0.33, bluffFreq: 0.12, notes: "理論" },
  { id: 10, name: "タクマ", tier: "全国", style: "守備型", strength: 3, trait: "安定", aggr: 0.35, tight: 0.8, drawRate: 0.3, bluffFreq: 0.05, notes: "守備" },
  { id: 11, name: "リョウ", tier: "全国", style: "ブラファー", strength: 4, trait: "読み", aggr: 0.48, tight: 0.25, drawRate: 0.45, bluffFreq: 0.25, notes: "ブラフ" },
  { id: 12, name: "メイ", tier: "全国", style: "タイナグレ", strength: 4, trait: "明確", aggr: 0.55, tight: 0.65, drawRate: 0.36, bluffFreq: 0.18, notes: "TAG" },
  { id: 13, name: "鉄強", tier: "世界", style: "超攻撃", strength: 5, trait: "圧倒", aggr: 0.8, tight: 0.4, drawRate: 0.5, bluffFreq: 0.18, notes: "世界最強" },
  { id: 14, name: "冷徹の女王", tier: "世界", style: "読み特化", strength: 5, trait: "読解", aggr: 0.48, tight: 0.8, drawRate: 0.3, bluffFreq: 0.08, notes: "読解+" },
  { id: 15, name: "博士", tier: "世界", style: "理論極", strength: 5, trait: "策略", aggr: 0.42, tight: 0.78, drawRate: 0.28, bluffFreq: 0.05, notes: "理論極" },
  { id: 16, name: "ゼロ", tier: "世界", style: "完全AI型", strength: 5, trait: "無垢同", aggr: 0.66, tight: 0.45, drawRate: 0.44, bluffFreq: 0.15, notes: "最高" },
  { id: 17, name: "ルイ", tier: "地方", style: "バランス", strength: 2, trait: "準強", aggr: 0.52, tight: 0.5, drawRate: 0.37, bluffFreq: 0.14, notes: "準強" },
  { id: 18, name: "スズ", tier: "地方", style: "ルーズ", strength: 1, trait: "対人", aggr: 0.38, tight: 0.32, drawRate: 0.5, bluffFreq: 0.17, notes: "ルーズ" },
  { id: 19, name: "ケン", tier: "店舗", style: "アグレ", strength: 1, trait: "押し", aggr: 0.62, tight: 0.4, drawRate: 0.42, bluffFreq: 0.2, notes: "押し" },
  { id: 20, name: "ユイ", tier: "全国", style: "バランス", strength: 3, trait: "速応", aggr: 0.53, tight: 0.57, drawRate: 0.41, bluffFreq: 0.13, notes: "速応" },
];
