#!/usr/bin/env node
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, "..");
const docsDir = path.join(repoRoot, "src", "docs");
const i18nDir = path.join(repoRoot, "src", "i18n");
const variantsPath = path.join(repoRoot, "src", "games", "config", "multiGameList.json");

const CATEGORY_LABELS = {
  "board": "Board / Hold'em / Omaha",
  "triple-draw": "Triple Draw",
  "single-draw": "Single Draw",
  "dramaha": "Dramaha",
  "stud": "Stud",
};

function buildSummary(variant) {
  const bits = [];
  if (variant.holeCards) bits.push(`${variant.holeCards} cards`);
  if (variant.drawRounds) {
    bits.push(`${variant.drawRounds} draw${variant.drawRounds > 1 ? "s" : ""}`);
  } else if (variant.board?.type) {
    bits.push(`Board ${variant.board.type}`);
  } else if (variant.stud) {
    bits.push("Stud streets");
  }
  if (variant.betting) bits.push(variant.betting);
  if ((variant.evaluators ?? []).some((tag) => tag.includes("split"))) {
    bits.push("Split pot");
  }
  return bits.join("; ");
}

async function loadVariants() {
  const raw = await readFile(variantsPath, "utf8");
  const sanitized = raw.replace(/^\uFEFF/, "");
  return JSON.parse(sanitized);
}

async function writeVariantMetadata(variants) {
  const payload = {
    generatedAt: new Date().toISOString(),
    total: variants.length,
    variants,
  };
  const outPath = path.join(docsDir, "variant_metadata.json");
  await writeFile(outPath, JSON.stringify(payload, null, 2), "utf8");
  console.log(`Saved ${outPath}`);
}

async function writeVariantI18n(variants) {
  await mkdir(i18nDir, { recursive: true });
  const entries = {};
  variants.forEach((variant) => {
    entries[variant.id] = {
      name: variant.name,
      description: variant.description ?? "",
    };
  });
  const outPath = path.join(i18nDir, "variants.ja.json");
  await writeFile(outPath, JSON.stringify(entries, null, 2), "utf8");
  console.log(`Saved ${outPath}`);
}

async function writeCatalogDoc(variants) {
  await mkdir(docsDir, { recursive: true });
  const lines = [
    "# Game Catalog",
    "",
    "Auto-generated by scripts/exportVariants.mjs.",
    "",
  ];

  Object.entries(CATEGORY_LABELS).forEach(([category, label]) => {
    lines.push(`## ${label}`);
    lines.push("");
    lines.push("| ID | Name | Status | Betting | Notes |");
    lines.push("| --- | --- | --- | --- | --- |");
    variants
      .filter((variant) => variant.category === category)
      .forEach((variant) => {
        const notes = buildSummary(variant);
        lines.push(
          `| ${variant.id} | ${variant.name} | ${variant.status ?? "planned"} | ${variant.betting} | ${notes} |`
        );
      });
    lines.push("");
  });

  const outPath = path.join(docsDir, "game_catalog.md");
  await writeFile(outPath, lines.join("\n"), "utf8");
  console.log(`Saved ${outPath}`);
}

async function main() {
  const variants = await loadVariants();
  await writeVariantMetadata(variants);
  await writeVariantI18n(variants);
  await writeCatalogDoc(variants);
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
