export const PRO_MIXED_PRESETS = [
  {
    id: "mix-horse-pro",
    name: "HORSE Pro",
    formatLabel: "HORSE",
    description: "5-game fixed-limit rotation used in pro series.",
    selectionMode: "FIXED",
    handsPerGame: 8,
    allowDuplicates: false,
    selectedGameIds: ["B02", "B06", "ST3", "ST1", "ST2"],
  },
  {
    id: "mix-8game-pro",
    name: "8-Game Pro",
    formatLabel: "8-Game",
    description: "WSOP-style 8-game mixed rotation.",
    selectionMode: "FIXED",
    handsPerGame: 6,
    allowDuplicates: false,
    selectedGameIds: ["B01", "B02", "B06", "ST3", "ST1", "ST2", "D01", "B05"],
  },
  {
    id: "mix-10game-pro",
    name: "10-Game Pro",
    formatLabel: "10-Game",
    description: "Upper Mix adding Badugi and NL 2-7 SD.",
    selectionMode: "FIXED",
    handsPerGame: 6,
    allowDuplicates: false,
    selectedGameIds: ["B01", "B02", "B06", "ST3", "ST1", "ST2", "D01", "B05", "D03", "S01"],
  },
  {
    id: "mix-pro-dealers-choice",
    name: "Dealer's Choice Pro",
    formatLabel: "Pro Dealer's Choice",
    description: "Weighted random dealer’s choice with hard/soft bans.",
    selectionMode: "WEIGHTED",
    handsPerGame: 4,
    allowDuplicates: true,
    selectedGameIds: ["B01", "B05", "B06", "B09", "ST1", "ST2", "ST3", "D01", "D03", "S01"],
    weightedTable: {
      B01: 2,
      B05: 2,
      B06: 1.5,
      B09: 0.5,
      ST1: 1,
      ST2: 1,
      ST3: 1,
      D01: 1,
      D03: 1,
      S01: 1,
    },
    softBans: ["B09"],
    hardBans: [],
  },
  {
    id: "mix-pro-category",
    name: "Category Rotation",
    formatLabel: "Category Dealer's Choice",
    description: "Category-based dealer’s choice with custom pools.",
    selectionMode: "CATEGORY",
    handsPerGame: 4,
    allowDuplicates: true,
    selectedGameIds: ["B01", "B02", "B05", "B06", "ST1", "ST2", "ST3", "D01", "D03", "S01", "H01", "H02"],
    categoryRules: {
      weights: {
        board: 3,
        stud: 2,
        "triple-draw": 2,
        "single-draw": 1,
        dramaha: 1,
      },
      pools: {
        board: ["B01", "B02", "B05", "B06"],
        stud: ["ST1", "ST2", "ST3"],
        "triple-draw": ["D01", "D03", "D05"],
        "single-draw": ["S01", "S04"],
        dramaha: ["H01", "H02", "H06"],
      },
    },
    hardBans: [],
    softBans: [],
  },
];
